### ISSUE TITLE
asiosdk2.3.1.zip not available on steinberg's website

### ISSUE THREAD

**Issue by constantitus** [internethering/hering-overlay#15]
media-libs/asio-sdk-2.3.1 requires asiosdk2.3.1.zip which isn't available since they updated to 2.3.3.
I need it to compile app-emulation/wineasio.

https://www.steinberg.net/developers/

![image](https://user-images.githubusercontent.com/118078873/230489665-c48ef0a2-bc19-4372-af4a-c489ffd9db8f.png)

also, distfiles is now in /var/cache

**Comment by internethering** [comment]
sry for late response, I updated the ebuild meanwhile
