### ISSUE TITLE
monero-core fails to build

### ISSUE THREAD

**Issue by Nexion** [internethering/hering-overlay#4]
Building 0.10.3.1
[build.log](https://gist.github.com/Nexion/a1d7a791889de0ca70d5fdaa06204c27)

**Comment by Nexion** [comment]
Almost the same with 0.11.0.0:
[build.log](https://gist.github.com/Nexion/aa7b6cb111781982cf7d4c2e1c17503a#file-build-log)

**Comment by internethering** [comment]
thank you for fixing. I removed old 0.10.3.1.
